#!/bin/bash

#  updated on 17.05.2015 16:11:02

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  

#################################################################
# Design based on IceFox script                                 #
# Modified, adapted and improved by pekman and excalibur1234    #
# translation by spylinux [spylinux@openmailbox.org]            #
# Contact and suggestions: pekman@openmailbox.org               #
# Freenode: #manjaropek #manjaro-geek #manjaro                  #
# Topic discussion                                              #
#           http://polr.me/pacli1                               #
#           http://polr.me/pacli2                               #
#################################################################

# set colors
RED='\e[41m'
BLUE='\e[44m'
ORANGE='\e[46m'
NC='\e[0m'
    while true; do
    clear
    echo ""
    echo -e "                   \e[47;3;32m Bash Frontend para o Pacman/Yaourt - pacli \033[0m "
    echo -e "                \e[33;5;1m (✌╰_╯)☞ \e[m$RED ATENÇÃO! USE COM CUIDADO $NC\e[33;5;1m ¯\_(ツ)_/¯ \e[m"
    echo -e " ┌────────────────────────────────────────────────────────────────────────────┐"
    echo -e " │  $NC  1 $NC  Atualizar Sistema  \e[32;5;1m ───▄████▄───── \033[0m     $NC  2 $NC  Otimizar Mirrors      │"
    echo -e " │  $NC  3 $NC  Otimizar Base      \e[32;5;1m ──███▄█▀────── \033[0m     $NC  4 $NC  Limpar Cache          │"
    echo -e " │  $NC  5 $NC  Buscar Pacote      \e[32;5;1m ─▐████──█──█── \033[0m     $NC  6 $NC  Informação do Pacote  │"
    echo -e " │  $NC  7 $NC  Instalar Pacote    \e[32;5;1m ──█████▄────── \033[0m     $NC  8 $NC  Detalhar Pacote       │"
    echo -e " │  $NC  9 $NC  Remover Pacote     \e[32;5;1m ───▀████▀───── \033[0m     $NC 10 $NC  Remover Pacote + Deps │"
    echo -e " │  $NC 11 $NC  Listar Pacotes Órfãos                   $NC 12 $NC  Remover Pacotes Órfãos│"
    echo -e " │  $NC 13 $NC  Lista Local                             $NC 14 $NC  Árvore de Dependências│"
    echo -e " │  $NC 15 $NC  Pacotes Instalados                      $NC 16 $NC  Corrigir Erros        │"
    echo -e " └────────────────────────────────────────────────────────────────────────────┘"
    echo ""
    echo -e " ┌────────────────────────────────────────────────────────────────────────────┐"
    echo -e " │  $NC 17 $NC  Atualizar AUR                           $NC 18 $NC  Buscar no AUR         │"
    echo -e " │  $NC 19 $NC  Instalar do AUR                         $NC 20 $NC  Remover do AUR        │"
    echo -e " │  $NC 21 $NC  Remover do AUR + Deps                   $NC 22 $NC  Instalado do AUR      │"
    echo -e " └────────────────────────────────────────────────────────────────────────────┘"
    echo ""
    echo -e " $BLUE Selecione um número entre 1 e 22 e aperte [Enter]$NC $RED 23 Sair do pacli$NC"
    echo ""
    read choix
    case $choix in
        1)
            echo
            sudo pacman -Syyuu
            echo ""
            echo -e "\033[42;1;37m Seu sistema está atualizado. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        2)
            echo
            sudo pacman-mirrors -g && sudo pacman -Syy
            echo ""
            echo -e "\033[42;1;37m EScolhido mirror mais rápido. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        3)
            echo
            sudo pacman-optimize
            echo ""
            echo -e "\033[42;1;37m Base de Dados do Pacman otimizada. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        4)
            echo
            paccache -ruk0
            paccache -rk3
            echo ""
            echo -e "\033[42;1;37m Versões de pacotes desnecessários e antigos removidos. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        5)
            echo ""
            echo "Você deseja buscar um pacote? Digite o nome abaixo e aperte ENTER"
            echo ""
            read searchpackage
            pacman -Ss $searchpackage
            echo ""
            echo -e "\033[42;1;37m A busca está completa. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        6)
            echo ""
            echo "Você deseja verificar alguma informação específica de um pacote? Digite o nome abaixo e aperte ENTER"
            echo ""
            read searchpackage
            pacman -Si $searchpackage
            echo ""
            echo -e "\033[42;1;37m A busca por informação acabou. Para voltar ao pacli aperte ENTER \033[0m"
            read 
            ;;
        7)
            echo ""
            echo "Você deseja instalar um pacote? Digite o nome abaixo e aperte ENTER"
            echo ""
            read installpackage
            sudo pacman -S $installpackage
            echo ""
            echo -e "\033[42;1;37m A instalação do pacote terminou. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        8)
            echo ""
            echo "Você deseja verificar alguma informação específica de um pacote? Digite o nome abaixo e aperte ENTER"
            echo ""
            read searchpackage
            pacman -Qi $searchpackage
            echo ""
            echo -e "\033[42;1;37m Toda informação exibida. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        9)
            echo ""
            echo "Você deseja desinstalar um único pacote? Todas Dependências serão mantidas como órfãs. Digite o nome abaixo e aperte ENTER"
            echo ""
            read uninstallpackage
            sudo pacman -R $uninstallpackage
            echo ""
            echo -e "\033[42;1;37m Ação concluída. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        10)
            echo ""
            echo "Você deseja desinstalar um pacote e todas suas dependências? Digite o nome abaixo e aperte ENTER"
            echo ""
            read uninstallpackage
            sudo pacman -Rsn $uninstallpackage
            echo ""
            echo -e "\033[42;1;37m Ação concluída. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        11)
            echo ""
            echo "Exibir todos pacotes órfãos"
            pacman -Qqdt
            echo ""
            echo -e "\033[42;1;37m Verificação concluída. Para retornar ao pacli aperte ENTER \033[0m"
            read        
            ;;
        12)
            echo ""
            echo "Você deseja desinstalar os pacotes órfãos incluindo todas dependências? Digite ENTER para continuar."
            echo ""
            read uninstallpackage
            sudo pacman -Rns $(pacman -Qqdt)
            echo ""
            echo -e "\033[42;1;37m Tarefa concluída. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        13)
            echo ""
            echo "Você deseja listar todos arquivos locais de um pacote? Digite abaixo o nome do pacote e aperte ENTER"
            echo ""
            read Packcage
            pacman -Ql $Packcage
            echo ""
            echo -e "\033[42;1;37m Tarefa concluída. Para voltar ao pacli aperte ENTER \033[0m"
            read 
            ;;
        14)
            echo ""
            echo "Você deseja exibir a árvore de dependências de um pacote? Digite abaixo o nome do pacote e aperte ENTER"
            echo ""
            read Packcage
            pactree $Packcage >> pactree.txt; $EDITOR pactree.txt; rm pactree.txt
            echo ""
            echo -e "\033[42;1;37m Tarefa concluída. Agora aperte ENTER \033[0m"
            read
            ;;
        15)
            echo ""
            cd /tmp; pacman -Qet >> packs.txt; $EDITOR packs.txt; rm packs.txt
            echo ""
            echo -e "\033[42;1;37m Sua lista de pacotes foi exportada. Agora aperte ENTER \033[0m"
            read     
            ;;
            
        16)
            echo ""
            sudo rm -f /var/lib/pacman/db.lck && sudo pacman-mirrors -g && sudo pacman -Syy
            echo ""
            echo -e "\033[42;1;37m Todos erros do Pacman foram corrigidos. Agora aperte ENTER \033[0m"
            read     
            ;;
        17)
            echo ""
            echo "Para atualizar os pacotes do AUR aperte ENTER. Então forneça sua senha."
            yaourt -Syyuua
            echo ""
            echo -e "\033[42;1;37m Nada a fazer. Para voltar ao pacli aperte ENTER \033[0m"
            read     
            ;;
        18)
            echo ""
            echo "Você deseja buscar um pacote no AUR? Aperte ENTER para continuar."
            echo ""
            read searchpackage
            yaourt -Ss $searchpackage 
            echo ""           
            echo -e "\033[42;1;37m Busca concluída. Para retornar ao pacli aperte ENTER \033[0m"
            read
            ;;
        19)
            echo ""
            echo "Você deseja instalar um pacote do AUR? Digite abaixo o nome correto do pacote e aperte ENTER"
            echo ""
            read Packcage
            yaourt -S $Packcage
            echo ""
            echo -e "\033[42;1;37m Tarefa concluída. Para voltar ao pacli aperte ENTER \033[0m"
            read 
            ;;
        20)
            echo ""
            echo "Você deseja remover um único pacote do AUR? Todas Dependências serão mantidas como órfãs. Digite abaixo o nome correto do pacote e aperte ENTER"
            echo ""
            read Packcage
            yaourt -R $Packcage
            echo ""
            echo -e "\033[42;1;37m Tarefa concluída. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        21)
            echo ""
            echo "Você deseja remover um pacote do AUR incluindo todas suas dependências? Digite abaixo o nome correto do pacote e aperte ENTER"
            echo ""
            read Packcage
            yaourt -Rsn $Packcage
            echo ""
            echo -e "\033[42;1;37m Tarefa concluída. Para voltar ao pacli aperte ENTER \033[0m"
            read
            ;;
        22)
            echo ""
            cd /tmp; pacman -Qem >> unoficial.txt; $EDITOR unoficial.txt; rm unoficial.txt
            echo ""
            echo -e "\033[42;1;37m Sua lista de pacotes foi exportada. Agora aperte ENTER \033[0m"
            read     
            ;;
        23)
            clear && exit
            read
            ;;
        *)
            echo -e "$RED Opção errada $NC"
            echo "Aguarde e tente novametne depois..."
            echo ""
            sleep 3
            clear
            ;;
    esac
    done
fi
